baseURL = 'https://worldlightyjx.github.io/'
theme = 'PaperMod'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  displayFullLangName = true
  mainSections = ['posts']

[languages.zh]
  contentDir = 'content/zh'
  label = '中文'
  locale = 'zh-CN'
  title = 'Yang的思想空间'
  weight = 1
  hasCJKLanguage = true

[[languages.zh.params.socialIcons]]
  name = 'github'
  url = 'https://github.com/worldlightyjx'

[[languages.zh.params.socialIcons]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/jiaxin-yang-82776b91'

[[languages.zh.menus.main]]
  name = '首页'
  pageRef = '/'
  weight = 10

[[languages.zh.menus.main]]
  name = '关于'
  pageRef = '/about'
  weight = 20

[[languages.zh.menus.main]]
  name = '归档'
  pageRef = '/archives'
  weight = 30

[languages.en]
  contentDir = 'content/en'
  label = 'English'
  locale = 'en-US'
  title = "Yang's Mind Space"
  weight = 2

[[languages.en.params.socialIcons]]
  name = 'github'
  url = 'https://github.com/worldlightyjx'

[[languages.en.params.socialIcons]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/jiaxin-yang-82776b91'

[[languages.en.menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[languages.en.menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 20

[[languages.en.menus.main]]
  name = 'Archives'
  pageRef = '/archives'
  weight = 30
